### ISSUE TITLE
Use sophus as a git sub-module instead of copied files

### ISSUE THREAD

**Issue by slovak194** [craigstar/SophusPy#2]
Hi!

This is the great initiative to make pybind11 bindings for Sophus! I'm happy that I have a chance to create the first issue/proposal for that:

Is there any reason against replacing sophus/include/original with git submodule?
It would allow easy tracking changes in original Sophus repo.

Thanks for the answer!

**Comment by craigstar** [comment]
I am glad to receive your question. Actually, when I created this repo, I wanted to make it simple and  fast done, so I did not use git submodule.  However, its good to make this more advanced. I will do it sometime, and you are also welcome to contribute.

**Comment by craigstar** [comment]
As I refactored the code, I found that the source code is not compatible for windows when I compile using github actions. So I still use the old version, which is enough for my purpose.
