### ISSUE TITLE
Fails for install with pip on Ubuntu 18.04

### ISSUE THREAD

**Issue by NikolausDemmel** [craigstar/SophusPy#3]
Hi,

thanks for the library, it works great. So far on macos like a charm.

On Ubuntu 18.04 however, I cannot install it via pip since it fails to compile, see https://github.com/pybind/pybind11/issues/890#issuecomment-570630304 

It seems that the system version of pybind11 is too old (2.0.1) such that you get a compile error like

```
    /tmp/pip-install-gzn3gvm0/sophuspy/sophus/sophuspy.cpp:9:16: error: expected constructor, destructor, or type conversion before ‘(’ token
     PYBIND11_MODULE(sophuspy, m)
```

On the other hand, installing pybind11 via pip doesn't include the cmake modules (see https://github.com/pybind/pybind11/issues/1628#issuecomment-570641963), so with that the compilation of sophuspy also fails.

Do you have a suggestion on how to workaround this? Can sophuspy be made compatible with pybind11 2.0.1? Looks like getting pybind11 from pip to install cmake modules is a longer story, and building sophuspy without those cmake modules is probably also a pain...

If you manually install custom build pybind11 with `sudo make install` or install pybind11 with anaconda, it would probably work, but both options are out of the question as requirements to put on users of my scripts (that use sophuspy), unfortunately.

**Comment by NikolausDemmel** [comment]
Looks like an alternative to building with cmake might by using setuptools instead, see https://github.com/pybind/python_example (I can build/install this python_example fine with pip using pybind11 from pip).

**Edit:** See also: https://pybind11.readthedocs.io/en/stable/compiling.html#building-with-setuptools

**Comment by NikolausDemmel** [comment]
FWIW, you can can manually download and install pybind11 locally and then install sophuspy with that. Still not ideal, but workable.

```
git clone https://github.com/pybind/pybind11.git
cd pybind11
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install/
make -j8
make install
pybind11_DIR=$PWD/../install/share/cmake/pybind11/ pip3 install --user sophuspy
```

**Comment by craigstar** [comment]
Hi, installing pybind11 manually is my answer and you've solved the problem. So far as I know, pip install pybindd11 only include header files, it's not complete. 
You're right, currently it is not ideal. To make the project independent, I need to google and do some research. Thank you for your advise.

**Comment by NikolausDemmel** [comment]
pybind11 master now installs cmake modules also from pip: https://github.com/pybind/pybind11/issues/1628#issuecomment-697331539

I don't think it's released yet.
