### ISSUE TITLE
Initialize SE3 using list 4x4

### ISSUE THREAD

**Issue by lanfeiying** [craigstar/SophusPy#4]
Hi, 
Thank you for this great open source project!
I have a problem when using this python library.
I have a 4x4 SE3 matrix:
```
  9.9935108e-001	 -1.5576084e-002	  3.1508941e-002	 -1.2323361e-001	
  9.2375092e-003	  9.8130137e-001	  1.9211653e-001	 -1.1206967e+000	
 -3.3912845e-002	 -1.9170459e-001	  9.8083067e-001	 -9.8870575e-001	
  0.0000000e+000	  0.0000000e+000	  0.0000000e+000	  1.0000000e+000	
```
This is stored in a list `matrix`.
I am trying to initialize an SE3 object `se3` as below:
```
import sophus as sp

matrix = [ .... .... .... .... ]

se3 = sp.SE3(matrix)
```
when I run this script, it shows the error:
```
Sophus ensure failed in function 'Sophus::SO3<Scalar_, Options>::SO3(const Transformation&) [with Scalar_ = double; int Options = 0; Sophus::SO3<Scalar_, Options>::Transformation = Eigen::Matrix<double, 3, 3>]', file '/tmp/pip-install-hgs_4p__/sophuspy/sophus/include/original/so3.hpp', line 424.
R is not orthogonal:
    0.999938 7.05962e-08 1.04281e-07
7.05962e-08    0.999946 5.40777e-07
1.04281e-07 5.40777e-07     0.99993
Aborted (core dumped)
```

As we see, it fails because the rotation matrix is not orthogonal. I have no idea why the rotation part is not correct.
The rotation part should be:
```
9.9935108e-001	 -1.5576084e-002	  3.1508941e-002
9.2375092e-003	  9.8130137e-001	  1.9211653e-001
-3.3912845e-002	 -1.9170459e-001	  9.8083067e-001
```
instead of the error message:
```
 0.999938 7.05962e-08 1.04281e-07
7.05962e-08    0.999946 5.40777e-07
1.04281e-07 5.40777e-07     0.99993
```

**Comment by craigstar** [comment]
Hi, that's easy to fix. Sophus requires rotation matrix to be orthogonal restrictively. 

In sophuspy, there's a trick written in README part 6. Just use `new_orthogonal_R = sp.to_orthogonal(your_old_R)`, then boom!
PS. `T = sp.SE3(new_orthogonal_R, translation)`

Let me know if my answer helps.

**Comment by lanfeiying** [comment]
@craigstar 
Hi, 
Thank you very much for the answer! It really helps!
I am wondering if this package could provide the function of transforming SE3 to a quaternion?

**Comment by craigstar** [comment]
Sophus uses eigen quaternion, so there's no quaternion API in sophuspy. I know there are python packages specifically for quaternion, and it'd be easy to transform from SO3 matrix. So maybe you can take a look at `pyquaternion` , `numpy-quaternion` and `scipy.spatial.transform`
