### ISSUE TITLE
Cannot Install Using PIP: Could not find a package configuration file provided by "pybind11"

### ISSUE THREAD

**Issue by aaaa-trsh** [craigstar/SophusPy#5]
When running `pip install sophuspy` there is an error when building the wheel for the module in setup.py:
![image](https://user-images.githubusercontent.com/47063067/114952831-ff4d0a80-9e0b-11eb-8edc-87a874e00f3e.png)
The main meat of the error seems to be   

       Could not find a package configuration file provided by "pybind11" with any
      of the following names:

      pybind11Config.cmake
      pybind11-config.cmake

    Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
    "pybind11_DIR" to a directory containing one of the above files.  If
    "pybind11" provides a separate development package or SDK, be sure it has
    been installed.'

Even after running `pip install pybind11[global]` - as recommended [here  ](https://github.com/pybind/pybind11/issues/1379) - there seems to be no sign of pybind11 in my CMake installation.

If pybind even is installed, how do I add the installation prefix to the CMAKE_PREFIX_PATH?

Can anyone help me install this?

**Comment by craigstar** [comment]
This is duplicated with: https://github.com/craigstar/SophusPy/issues/3.
 Also, please read the README Requirements

**Comment by craigstar** [comment]
closing because of no more response
