### ISSUE TITLE
sophuspy colab build fail

### ISSUE THREAD

**Issue by DL-SF** [craigstar/SophusPy#6]
sophuspy failed building wheel in colab

**Comment by craigstar** [comment]
I'm sorry that I don't know what colab means. Please provide more details

**Comment by DL-SF** [comment]
Hi,
Could you please let us know how to run the VINet code(sophuspy not building  in Google Colab)? We
are facing problems in installing the sophus.py file so that we can run
this in Jupyter Notebooks. Also, where do we provide the sensor data (
visual and inertial) collected from hololens in the VINet code.

**Comment by craigstar** [comment]
Sorry to reply late. New version 1.0.1 has released, I have solved pybind11 build problem. hope this would help.

**Comment by craigstar** [comment]
Closing cause no more building needed.
