### ISSUE TITLE
FWIW, you can can manually download and install pybind11 locally and then install sophuspy with that. Still not ideal, but workable.

### ISSUE THREAD

**Issue by xfDing815** [craigstar/SophusPy#7]
FWIW, you can can manually download and install pybind11 locally and then install sophuspy with that. Still not ideal, but workable.

```
git clone https://github.com/pybind/pybind11.git
cd pybind11
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install/
make -j8
make install
pybind11_DIR=$PWD/../install/share/cmake/pybind11/ pip3 install --user sophuspy
```

_Originally posted by @NikolausDemmel in https://github.com/craigstar/SophusPy/issues/3#issuecomment-570670449_

**Comment by craigstar** [comment]
New version 1.0.1 has solved the pybind11 problem, Hooray
